server {
  listen 80;
  server_name _;

  root  /usr/share/nginx/html/src;
  index index.html;


  location / {
    try_files $uri $uri/ /index.html;
  }

  location = /favicon.ico {
    log_not_found off;
    access_log off;
    return 204;
  }

  location /api/ {
    proxy_pass http://my-ollama:11434/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header Connection "";
    proxy_buffering off;
    chunked_transfer_encoding on;
  }
}
