services:
  # web:
  #   image: nginx:latest
  #   ports: ["8080:80"]
  #   volumes:
  #     - ./default.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./frontend:/usr/share/nginx/html:ro
  #   depends_on:
  #     - my-ollama
  #   command: ["nginx", "-g", "daemon off;"]
  my-ollama:
    image: ollama/ollama
    container_name: ollama-service
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - 11434:11434
